import fs from "node:fs";
import path from "node:path";

import { nativeProjectDir } from "./nativeProject.js";

/**
 * OS permissions an app declares in its own package.json, so it never has
 * to touch the framework-owned `.chain/native/`:
 *
 *   "chain": { "permissions": { "microphone": "Why the app records audio." } }
 *
 * Each value is the sentence the OS shows in its permission prompt. See
 * agent-docs/framework/command/README.md's "App permissions" section.
 */
export interface AppPermissions {
  microphone?: string;
  speechRecognition?: string;
  systemAudio?: string;
}

const PLIST_KEYS: Record<keyof AppPermissions, string> = {
  microphone: "NSMicrophoneUsageDescription",
  speechRecognition: "NSSpeechRecognitionUsageDescription",
  systemAudio: "NSAudioCaptureUsageDescription"
};

// Without it, a signed build with the hardened runtime gets silence from
// the microphone instead of a TCC prompt.
const AUDIO_INPUT_ENTITLEMENT = "com.apple.security.device.audio-input";

// Marks the two plist files as ours, so a hand-written Info.plist is
// never overwritten or deleted.
const GENERATED_MARKER =
  '<!-- GENERATED by chain from package.json "chain.permissions" — do not edit. -->';

export const ENTITLEMENTS_FILE = "Entitlements.plist";

export function readPermissions(cwd: string): AppPermissions {
  const pkg = JSON.parse(fs.readFileSync(path.join(cwd, "package.json"), "utf8")) as {
    chain?: { permissions?: Record<string, unknown> };
  };
  const declared = pkg.chain?.permissions ?? {};
  const permissions: AppPermissions = {};
  for (const [key, value] of Object.entries(declared)) {
    if (!(key in PLIST_KEYS)) {
      throw new Error(
        `package.json "chain.permissions.${key}" isn't a permission Chain knows — use one of: ${Object.keys(PLIST_KEYS).join(", ")}.`
      );
    }
    if (typeof value !== "string" || !value.trim()) {
      throw new Error(
        `package.json "chain.permissions.${key}" must be the sentence the OS shows when it asks the user.`
      );
    }
    permissions[key as keyof AppPermissions] = value.trim();
  }
  return permissions;
}

function escapeXml(text: string): string {
  return text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

function plist(entries: string[]): string {
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n' +
    `${GENERATED_MARKER}\n` +
    '<plist version="1.0">\n<dict>\n' +
    entries.join("") +
    "</dict>\n</plist>\n"
  );
}

/** Writes `content` to `file`, or removes it when `content` is undefined —
 * but only a file this module generated. Returns whether anything changed. */
function syncGeneratedFile(file: string, content: string | undefined): boolean {
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : undefined;
  if (current !== undefined && !current.includes(GENERATED_MARKER)) {
    if (content !== undefined) {
      console.warn(
        `Warning: ${file} wasn't generated by chain, so package.json "chain.permissions" can't update it — ` +
          "move its keys into package.json and delete it."
      );
    }
    return false;
  }
  if (current === content) return false;
  if (content === undefined) fs.rmSync(file);
  else fs.writeFileSync(file, content);
  return true;
}

/**
 * Brings `.chain/native/Info.plist` and `Entitlements.plist` in line with
 * package.json's declared permissions. Tauri merges an `Info.plist` next
 * to tauri.conf.json into the app — embedded in the binary for `tauri
 * dev`, into the bundle for `tauri build` — so a declared permission
 * reaches both. Returns the declared permissions.
 */
export function syncPermissions(cwd: string): AppPermissions {
  const permissions = readPermissions(cwd);
  const nativeDir = nativeProjectDir(cwd);

  const infoEntries = Object.entries(permissions).map(
    ([key, description]) =>
      `\t<key>${PLIST_KEYS[key as keyof AppPermissions]}</key>\n\t<string>${escapeXml(description)}</string>\n`
  );
  const infoChanged = syncGeneratedFile(
    path.join(nativeDir, "Info.plist"),
    infoEntries.length > 0 ? plist(infoEntries) : undefined
  );
  syncGeneratedFile(
    path.join(nativeDir, ENTITLEMENTS_FILE),
    permissions.microphone
      ? plist([`\t<key>${AUDIO_INPUT_ENTITLEMENT}</key>\n\t<true/>\n`])
      : undefined
  );

  // `tauri dev` embeds Info.plist from generate_context!, a proc macro
  // that only reruns when the crate recompiles — Cargo doesn't track the
  // plist. Touching lib.rs makes the next build pick the change up.
  if (infoChanged) {
    const libRs = path.join(nativeDir, "src", "lib.rs");
    if (fs.existsSync(libRs)) {
      const now = new Date();
      fs.utimesSync(libRs, now, now);
    }
  }
  return permissions;
}

/** Extra `tauri build` args: the entitlements file, when one is needed.
 * Passed as a config override rather than written into tauri.conf.json, so
 * the tracked config stays the same whether or not a permission is declared. */
export function buildPermissionArgs(permissions: AppPermissions): string[] {
  if (!permissions.microphone) return [];
  return ["--config", JSON.stringify({ bundle: { macOS: { entitlements: ENTITLEMENTS_FILE } } })];
}

export function syncPermissionsOrExit(cwd: string): AppPermissions {
  try {
    return syncPermissions(cwd);
  } catch (error) {
    console.error(`Error: ${(error as Error).message}`);
    process.exit(1);
  }
}
