#!/usr/bin/env node
// Bakes chain-sdk's current git remote/commit and @chain/sdk's version into
// packages/cli/src/publishMeta.ts at build time.
//
// Why this has to be baked in rather than read at `chain init` runtime:
// once @chain/cli is installed from npm, there's no chain-sdk git checkout
// sitting next to it to introspect — the installed package is just compiled
// JS. So the values a scaffolded app needs (which commit of chain-core to
// depend on, which @chain/sdk version to depend on) must be captured here,
// while this script is still running inside a real chain-sdk clone.
//
// Run with --strict (used by `prepublishOnly`) to refuse publishing from a
// dirty working tree or a commit that hasn't been pushed to origin — a
// published @chain/cli pinned to an unreachable commit would break every
// `chain init`/`chain update` run against it.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const cliDir = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const strict = process.argv.includes("--strict");

function git(args, cwd) {
  return execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
}

const repoRoot = git(["rev-parse", "--show-toplevel"], cliDir);
const remoteUrl = git(["remote", "get-url", "origin"], repoRoot);
const rev = git(["rev-parse", "HEAD"], repoRoot);
const sdkVersion = JSON.parse(
  fs.readFileSync(path.join(repoRoot, "packages/sdk/package.json"), "utf8")
).version;

if (strict) {
  const dirty = git(["status", "--porcelain"], repoRoot);
  if (dirty) {
    console.error(
      "sync-meta --strict: working tree has uncommitted changes — commit (or stash) before publishing, " +
        "so @chain/cli doesn't pin chain-core to a commit that doesn't match what's actually being published."
    );
    process.exit(1);
  }
  const onRemote = execFileSync("git", ["branch", "-r", "--contains", rev], { cwd: repoRoot, encoding: "utf8" });
  if (!onRemote.trim()) {
    console.error(
      `sync-meta --strict: HEAD (${rev}) hasn't been pushed to any remote branch — push first, ` +
        "otherwise scaffolded apps will depend on a chain-core commit nobody else can fetch."
    );
    process.exit(1);
  }
}

const out =
  "// GENERATED by scripts/sync-meta.mjs — do not edit.\n" +
  "// Baked in at build time; see that script's comment for why.\n\n" +
  `export const CHAIN_CORE_GIT_URL = ${JSON.stringify(remoteUrl)};\n` +
  `export const CHAIN_CORE_REV = ${JSON.stringify(rev)};\n` +
  `export const CHAIN_SDK_VERSION = ${JSON.stringify(sdkVersion)};\n`;

fs.writeFileSync(path.join(cliDir, "src/publishMeta.ts"), out);
console.log(`sync-meta: chain-core@${rev.slice(0, 12)} (${remoteUrl}), @chain/sdk@${sdkVersion}`);
